/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Jose
 * Created: 23-abr-2019
 */
DROP TABLE EQUIPOS;
DROP TABLE PATROCINADOR;

CREATE TABLE PATROCINADOR (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(20) NOT NULL,
    DINERO VARCHAR(20),
    FECCONTRATO DATE,
    CONSTRAINT ID_PATROCINADOR_PK PRIMARY KEY (ID)
);

CREATE TABLE EQUIPOS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(40),
    NUMPILOTOS SMALLINT,
    PATROCINADOR INTEGER NOT NULL,
    PATROCINIO BOOLEAN,
    NUMEMPLEADOS SMALLINT,
    FECCREACION DATE,
    NUMCAMPEONATOS SMALLINT,
    NUMVICTORIAS SMALLINT,
    SALARIOMEDIOEQUIPO DECIMAL(7,2),
    FOTO VARCHAR(30),
    CONSTRAINT ID_EQUIPOS_PK PRIMARY KEY (ID),
    CONSTRAINT PATR_EQUIPOS_FK FOREIGN KEY (PATROCINADOR) REFERENCES PATROCINADOR (ID)
);